### ISSUE TITLE
Support for `osx-arm64`? ("nothing provides requested xeus-octave")

### ISSUE THREAD

**Issue by harshitpdoshi** [jupyter-xeus/xeus-octave#101]
* xeus-octave version: 0.1.0
* Operating System: Mac OS Ventura 13.2.1 (22D68)

### Description

I am trying to install Xeus-Octave to run and learn Octave using the Jupyter UI since that is what I have come to be comfortable with, the most.

### What I Did

I took the following steps to install `Xeus-Octave` up and running on my MacBook:
- Install Mamba
    - I have been using `PyEnv` for all my Python version management requirements and I installed Mamba using the following command:
    ```
    pyenv install mambaforge
    ```
    - The current Mamba version is as follows:
    ```
    ➜ mamba -V
    conda 23.1.0
    ```
- Try to install `Xeus-Octave` using the newly installed Mamba. For this, I initially tried to install the `xeus-octave` package inside an existing environment, which didn't work and I was seeing the following output from Mamba:
```
➜ mamba install -c conda-forge xeus-octave

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.3.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['xeus-octave']

conda-forge/osx-arm64                                         No change
conda-forge/noarch                                  11.4MB @   3.9MB/s  3.2s

Pinned packages:
  - python 3.11.*


Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested xeus-octave

The environment can't be solved, aborting the operation
```
    - After this, I tried to install `Xeus-Octave` in a fresh new environment as shown in the documentation but I am seeing the same output as above.
    
**Note**: I have tried these attempts numerous times several hours apart keeping in mind a slight suspicion that it might be a network issue or a CDN issue, but for each attempt, I am seeing the same output.

I believe this is happening due to an unavailability of a package for the `osx-arm64` architecture as inspected by me on the `conda-forge` package index.

**Comment by rapgenic** [comment]
> I believe this is happening due to an unavailability of a package for the `osx-arm64` architecture as inspected by me on the `conda-forge` package index.

You are right on this.

Unfortunately a few dependencies of xeus-octave are not yet packaged for `osx-arm64` architecture.

I'm having a look at it, to see if it's possible to build them for this architecture.

**Comment by rapgenic** [comment]
Hi, @HarshitDoshi, if you want to try it, we now have a `osx-arm64` build :tada:

**Comment by harshitpdoshi** [comment]
@rapgenic, this is amazing! Thank you very much for putting this together so quickly!

Let me start using it from now. I will finally be able to learn Octave in the environment I love.

I will provide feedback as and when I explore the build. Do let me know if there is any specific area which should be heavily tested.

🚀

**Comment by harshitpdoshi** [comment]
P.S. I will close this issue after I install the new build. Hope that's alright!

**Comment by SylvainCorlay** [comment]
I just test on a m1 laptop and the package seems to work as expected. Closing.
